### ISSUE TITLE
docker:stop has no option to remove associated volumes

### ISSUE THREAD

**Issue by djimenez** [rhuss/docker-maven-plugin#120]
If i docker:start a container that's supposed to have volumes, docker may create one or more automatic volumes for it which won't get removed without the "v" option:

https://docs.docker.com/reference/api/docker_remote_api_v1.17/#remove-a-container

"bind-mounts" don't get touched by this option, it only concerns the automatically created volume directories and their contents usually found under /var/lib/docker/vfs/dir/

It'd be nice if your remove container did this by default, or if you added an option to set the parameter.

thanks.

**Comment by rhuss** [comment]
Thanks for the PR. It is applied and availabl in the next release (1.2.4)
