### ISSUE TITLE
Pull link information from Dockerfile

### ISSUE THREAD

**Issue by jburell** [rhuss/docker-maven-plugin#124]
If I use a Dockerfile in my build configuration, with a link specified, it does not trigger a link-dependency during startup.

It should, in my oppinion, be such that Dockerfile settings get parsed from the dockerfile and gets overridden by build-settings that in turn get overridden by run-settings.

Want me to look into a solution for this? I think this applies to more settings than just linking.

**Comment by jgangemi** [comment]
can you post an example of such a Dockerfile? is this fig/compose related (which is not yet supported and probably a larger discussion)?

**Comment by jburell** [comment]
You are right. Was porting from a fig-file and forgot that link is a Run-parameter and not a Build-parameter. Are compose-support planned? I would really like having as little dependency on maven config as possible (for increased portability).

**Comment by rhuss** [comment]
Yes, compose support is planned (see #57). Closing this this ticket, feel free to reopen it if you still need support here.
