### ISSUE TITLE
Allow a Dockerfile for defining an Image to build

### ISSUE THREAD

**Issue by rhuss** [rhuss/docker-maven-plugin#13]
Similar to https://github.com/spotify/docker-maven-plugin it should be possible to further tune the parameters for building the data image:

* Allow a `Dockerfile`
* Entry Point

BTW, @rculbertson, wouldn't it be an option to merge efforts ? I.e. one of the highlights of this plugin is to use a plain maven-assembly-plugin decscriptor for creating the data container (which is much more flexible than including files via path only).

**Comment by jgangemi** [comment]
added in 0.11.1, closing
