### ISSUE TITLE
:ro seems broken

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#134]
This breaks mounting:

    <volume>${service.logs.folder}:/logs:ro</volume>

This mounts just fine:

    <volume>${service.logs.folder}:/logs</volume>

My suggestion: `:ro` is broken.

"Broken" means that I don't see the files written to `/logs` appear in whatever I point `${service.logs.folder}` to. They actually don't show up anywhere (not even in `/logs`).

Not sure if this is a Docker issue or a plugin issue, but I'm looking at this world through my Maven glasses.

**Comment by rhuss** [comment]
Doesn't ":ro" means that the volume is mounted read only **in the container** ? That means, that the container cannot write to `/logs` and hence it is clear, that there will be no data if the volume is mounted read only.

I checked the call to the remote API and it looks ok.

**Comment by sverhagen** [comment]
Duh-uh... my bad! Sorry for wasting your time!

**Comment by rhuss** [comment]
No problem ;-)
