### ISSUE TITLE
Debug logging verbosity

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#142]
When specifying the `-X` switch to Maven the entire payload of API calls is being logged, that includes large binaries. This kind of stuff:

    [0x0][0x0][0x0]PK[0x3][0x4][0x14][0x0][0x8][0x8][0x8][0x0]r[0x1][0x8a]F[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x9][0x0][0x4][0x0]META-INF/[0xfe][0xca][0x0][0x0][0x3][0x0]PK[0x7][0x8][0x0][0x0][0x0][0x0][0x2][0x0][0x0][0x0][0x0][0x0][0x0][0x0]PK[0x3][0x4]

I've tried to find where this is logged, to no avail yet, suggestions welcome. It might be in the plugin, but also somewhere in the httpclient library, as far as I can see.

    [DEBUG] http-outgoing-0 >> "COPY maven /service/[\n]"
    [DEBUG] http-outgoing-0 >> "CMD ["java","-jar","/service/artifactId-1.0.8-SNAPSHOT.jar"][\n]"
    [DEBUG] http-outgoing-0 >> "[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x0]... et cetera... and so on... more goes here... la-di-dah...

Please give me a hint and I might come with a pull request...

**Comment by sverhagen** [comment]
This is in fact coming from `HttpClient`. See my question [here](http://stackoverflow.com/questions/29619125/logging-for-dependencies-of-maven-plugin).

**Comment by jgangemi** [comment]
it will be interested to see what the answer to that is b/c there are times i wish i could suppress other things that get logged in debug mode.

**Comment by rhuss** [comment]
I agree, that's that a bit too much. But however as you said, that comes from the HttpClient and unfortunately I can't do much here. If you come up with a solution, please let me know. 

What you can always do is to pipe the output to `grep -v http-outgoing` (if you have the luck to be on a unix like machine).

If you don't mind I close this ticket, feel free to reopen it in case.

**Comment by sverhagen** [comment]
Not the solution that I was looking for, but you can possibly configure it for the local Maven installation as discussed [here](http://mail-archives.apache.org/mod_mbox/maven-users/201504.mbox/%3Cop.xw626ygrkdkhrr@robertscholte.dynamic.ziggo.nl%3E). I didn't try this.
