### ISSUE TITLE
Registry authentication config in settings.xml

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#146]
When setting server credentials in `settings.xml` the `id` of the server is needed. The `id` of the registry is taken from the image name, see `AuthConfigFactory.getRegistryFromImageNameOrDefault`. If the image name does not include the registry, this method will always return `registry.hub.docker.io`, regardless of what's given in `<registry>` elements (either for the image or globally). I think this is wrong. My registry happens to be `something-else`, but `<server> ... <id>something-else</id> ...` in my `settings.xml` is subsequently ignored (as it is searching for `registry.hub.docker.io`.

I can work around this by using `<id>registry.hub.docker.io</id>` in my `settings.xml`, but that's flawed (I see at least the risk of inadvertently offering my *private* credentials, while contacting the public Docker Registry.

**Comment by rhuss** [comment]
You are absolutely right, that shouldn't be the case. 

Sorry that I missed that issue (was busy lately but now after I have switched jobs I have more time to spend on this).

In fact the authentication info must be looked up from the registry provided (not only when specified as part of the name).

**Comment by sverhagen** [comment]
As mentioned in elsewhere:

> #146 is already fixed (but not yet pushed, need some better testing yet)

Would there be a 0.12.0-SNAPSHOT to test this on, I could try if it works for me now?

**Comment by rhuss** [comment]
Thanks !  I will push a 0.11.5-SNAPSHOT today with this fix and will let you know when I pushed it.

**Comment by rhuss** [comment]
I just made a release 0.11.5-M1 available from Maven central. It would be awesome if you could check this out. I believe that most of the registry issues are fixed and should now work as described in the documentation.

I will go through the issue and check them one-by-one.

Please let me know, whether this release works for you. A final 0.11.5 shouldn't be far away.

**Comment by sverhagen** [comment]
Tested this and it appears to be fixed. Thank you!

Would it be worth a new issue that the error message is so horribly *undescriptive* when there's no (correct) credentials in `settings.xml`?

    [ERROR] DOCKER> EOF (Internal Server Error: 500)

**Comment by rhuss** [comment]
I think the error message are nowadays better. At least with a docker daemon 1.6.1 they final report back an "Authentication error". On what version of Docker do you receive this dumb error message ?

**Comment by sverhagen** [comment]
I'm seeing the "Authentication error" on newer installs, should be good.
