### ISSUE TITLE
Configure registry auth token or take it from ~/.dockercfg

### ISSUE THREAD

**Issue by asssaf** [rhuss/docker-maven-plugin#147]
Would it be possible to get the auth token and send it with the X-Registry-Auth header instead of using plain username/password authentication?

As the docker host and cert path this should be configurable in maven or by default pick the default location from the filesystem (~/.dockercfg in this case)

**Comment by jgangemi** [comment]
this would be a good enhancement but i think we should wait to see how this https://github.com/docker/docker/pull/12009 shakes out before we do anything w/ it given we will have to decide if we want to be backwards compatible.

**Comment by rhuss** [comment]
I think, that's also a good idea. One could add it to the lookup chain for the credentials, that we already have:

* given as user/password as configuration or system properties
* in a `<server>` section in `~/.m2/settings.xml`
* and now: in `~/.dockercfg` 
* no user/password

**Comment by kuhnroyal** [comment]
docker now stores this in newer versions in `~\.docker\config.json`

**Comment by rhuss** [comment]
A similar fallback should happen when pushing to a OpenShift registry, where `oc login` creates tokens to be used a docker passwords. See also [here](https://docs.openshift.org/latest/admin_guide/install/docker_registry.html#access)

**Comment by rhuss** [comment]
Would be also cool to check for the timestap of the configuration files examined to decided which one to check first.

**Comment by rhuss** [comment]
Currently the plugin is using the auth also for pulling images when doing a build, and does this by extracting the username from the image to pull. This is obviously completely bogus, so we should change this to completely ignore the authentication for pulling. All at least ignore the usual configurations (system props, settings.xml) for authentication and only examine the docker config or openshift config.

See also https://github.com/fabric8io/fabric8-devops/issues/46

**Comment by rhuss** [comment]
Here's where the auth configuration is used for pulling (and where it extracts the username for the pull); https://github.com/rhuss/docker-maven-plugin/blob/d7a4ca8a90f0bddaaf71581a8642913c9b0ae19b/src/main/java/org/jolokia/docker/maven/AbstractDockerMojo.java#L386

An option could be also to include a global variable like `noPullAuthentication` for authenticaton.

**Comment by rhuss** [comment]
Implemented lookup of credentials within `~/.docker/config.json` as a fallback. Will be available in 0.13.7

For the fined grained authentication with pull vs. push and the Kubernetes support in `~/.kube/config` I will open dedicated issues.

**Comment by rhuss** [comment]
Follup issues created, so that this can be closed now.
