### ISSUE TITLE
Stop <command> from converting CMD to "exec form" (JSON array)

### ISSUE THREAD

**Issue by alan-czajkowski** [rhuss/docker-maven-plugin#149]
The following does not work:
```
<configuration>
  <images>
    <image>
      ...
      <build>
        ...
        <env>
          <ENV_VAR>some_value</ENV_VAR>
        </env>
        ...
        <command>echo $ENV_VAR</command>
      </build>
    </image>
  </images>
</configuration>
```
because ```<command>``` is converted to a _JSON array_ (exec form), and according the documentation http://docs.docker.com/reference/builder/#cmd
> Unlike the shell form, the exec form does not invoke a command shell. This means that normal shell processing does not happen. For example, ```CMD [ "echo", "$HOME" ]``` will not do variable substitution on ```$HOME```.

the documentation mentions this work-around:
> If you want shell processing then either use the shell form or execute a shell directly, for example: ```CMD [ "sh", "-c", "echo", "$HOME" ]```.

but this is _not_ correct, the documentation is wrong, in order for environment variable interpolation to work in _exec form_, in the ```CMD```, it must be structured like this: ```CMD [ "sh", "-c", "echo $HOME" ]```

but this _cannot_ be achieved through the plugin because ```<command>sh -c echo $ENV_VAR</command>``` results in ```CMD [ "sh", "-c", "echo", "$ENV_VAR" ]``` which is broken whereas we want ```CMD [ "sh", "-c", "echo $ENV_VAR" ]``` which is the desired result

The conversion of ```<command>``` to a _JSON array_ (exec form) should be disabled.

**Comment by rhuss** [comment]
With #130 being implemented you should be able to use the following in 0.12.0:

````xml
<configuration>
  <images>
    <image>
      ...
      <build>
        ...
        <env>
          <ENV_VAR>some_value</ENV_VAR>
        </env>
        ...
        <cmd>
           <shell>echo $ENV_VAR</shell>
        </cmd>
      </build>
    </image>
  </images>
</configuration>
````

0.12.0 will be out next week.
