### ISSUE TITLE
Multiple image elements not being handled correctly

### ISSUE THREAD

**Issue by BigSocial** [rhuss/docker-maven-plugin#153]
If I have this in my POM...

						<configuration>
							<verbose>true</verbose>
							<images>
								<image>
									<name>ois/tomcat7:latest</name>
									<build>
										<from>tutum/tomcat:7.0</from>
										<ports>
											<port>8080</port>
										</ports>
										<volumes>
										</volumes>
										<assembly>
											<basedir>/tomcat</basedir>
											<descriptor>tomcat-artifacts.xml</descriptor>
										</assembly>
									</build>
									<run>
										<env>
											<TOMCAT_PASS>tomcat</TOMCAT_PASS>
											<CATALINA_HOME>/tomcat</CATALINA_HOME>
											<OIS_DATABASE_DRIVER>com.mysql.jdbc.Driver</OIS_DATABASE_DRIVER>
											<OIS_DATABASE_URL>jdbc:mysql://chilnx9.us.ois.com:3306/ois1</OIS_DATABASE_URL>
											<OIS_DATABASE_PORT>3306</OIS_DATABASE_PORT>
											<OIS_DATABASE_USER>root</OIS_DATABASE_USER>
											<OIS_DATABASE_PASSWORD>root</OIS_DATABASE_PASSWORD>
											<OIS_STORAGE_BASE_PATH>/data/files/ois</OIS_STORAGE_BASE_PATH>
										</env>
										<ports>
											<port>8080:8080</port>
											<port>1099:1099</port>
											<port>1098:1098</port>
										</ports>
										<volumes>
											<bind>
												<volume>/usr/share/fonts:/usr/share/fonts</volume>
												<volume>/data/files/ois:/data/files/ois</volume>
											</bind>
										</volumes>
									</run>
								</image>
								<image>
									<name>ois/nginx:latest</name>
									<build>
										<from>nginx</from>
										<assembly>
											<basedir>/etc/nginx/</basedir>
											<descriptor>nginx-artifacts.xml</descriptor>
										</assembly>
									</build>
									<run>
										<ports>
											<port>80:80</port>
										</ports>
									</run>
								</image>
							</images>
						</configuration>
						<executions>
							<execution>
								<id>XYZ</id>
								<configuration>
									<dockerHost>http://chicasper.us.ois.com:4243</dockerHost>
									<images>
										<image>
											<name>ois/nginx:latest</name>
										</image>
									</images>
								</configuration>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>build</goal>
								</goals>
							</execution>
						</executions>

The Maven log output looks like this...

    [INFO] --- docker-maven-plugin:0.11.3:build (XYZ) @ ois ---
    [INFO] DOCKER> Creating image [ois/nginx:latest]
    [INFO] Reading assembly descriptor: /home/aime/workspace/OIS - Build and     deploy to development server/ois/src/main/docker/tomcat-artifacts.xml
    [INFO] Copying files to /home/aime/workspace/OIS - Build and deploy to development server/ois/target/docker/ois/nginx/latest/build/maven
    [INFO] Building tar: /home/aime/workspace/OIS - Build and deploy to development server/ois/target/docker/ois/nginx/latest/tmp/docker-build.tar
    [INFO] DOCKER> Step 0 : FROM tutum/tomcat:7.0
    [INFO] DOCKER> ---> e2c20fc9d50d
    [INFO] DOCKER> Step 1 : MAINTAINER docker-maven-plugin@jolokia.org
    [INFO] DOCKER> ---> Using cache
    [INFO] DOCKER> ---> 5b01cc8c2605
    [INFO] DOCKER> Step 2 : EXPOSE 8080
    [INFO] DOCKER> ---> Using cache
    [INFO] DOCKER> ---> 2103159aa324
    [INFO] DOCKER> Step 3 : VOLUME /tomcat
    [INFO] DOCKER> ---> Using cache
    [INFO] DOCKER> ---> 9f17ef5b79a8
    [INFO] DOCKER> Step 4 : COPY maven /tomcat/
    [INFO] DOCKER> ---> c9bc85fe7977
    [INFO] DOCKER> Removing intermediate container 8684eadc4006
    [INFO] DOCKER> Successfully built c9bc85fe7977

Notice that despite claiming it's building `ois/nginx:latest` it's actually building the tomcat image. This is as simple as I can get the issue. In reality, I have two images, one I want deployed to one server and one I want deployed to three servers. This issue is the first in my list of problems doing that with this plugin.

**Comment by rhuss** [comment]
I have to look into it but this is probably because of how Maven merges the configurations. You have a default configuration and a specific configuration bound to the lifecycle. These two are merged by default, see this [blog](http://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects) for details and also how to influence the merging.

I suspect that you want only one image build in the execution phase, but this is not how it works. If you want this, then you should use a single `<image>ois/nginx:latest</image>` config, i.e. 

````xml
<execution>
  <id>XYZ</id>
  <configuration>
       <dockerHost>http://chicasper.us.ois.com:4243</dockerHost>
       <image>ois/nginx:latest</image>
  </configuration>
  <phase>pre-integration-test</phase>
  <goals>
      <goal>build</goal>
  </goals>
</execution>
````

This will **select** an already configured image.

Please let me know, whether this works for you. I will have a look at the merging as it looks indeed a bit weird.

**Comment by BigSocial** [comment]
@rhuss Thanks! It wasn't clear that the image element could be pulled all the way down into the execution configuration but it makes sense to me now in hindsight.
