### ISSUE TITLE
Possible bug using remote registry

### ISSUE THREAD

**Issue by sverhagen** [rhuss/docker-maven-plugin#166]
I was under the impression that the following were equivalent:

    <image>
        <name>someName:someTag</name>
        <registry>someRegistry</registry>
    </image>

    <image>
        <name>someRegistry/someName:someTag</name>
    </image>

However, this does not appear to be the case. They are turned into the following (separate) REST requests, the former not leading to the right result (for me).

    POST /v1.15/images/someRegistry%2FsomeName:someTag/tag?repo=someName&tag=someTag

    POST /v1.15/images/create?fromImage=someRegistry%2FsomeName&tag=someTag

**Comment by rhuss** [comment]
Ok, I will have a look at it. Indeed, both should yield the same results.

**Comment by rhuss** [comment]
Both setups are quite similar, but not identically:

* In the first case, you create an image `someName:someTag` in you docker installation. You can refer to is e.g. with `docker run someName:someTag` and work with this name. If you need to push this to a remote registry, an extra **tag** `someRegistry/someName:someTag` must be created before this then can be pushed. That's the way how Docker works. What you see above is indeed this tag-step (there has been a creation step before for the simple name, but not shown).

* In the second case the name already is `someRegistry/someName:someTag` so no extra tag is required. 

However, /wr to a push, at the end both should give the same result in the registry: Namely, that the image `someRegistry/someName:someTag` gets pushed to the registry. 

If this doesn't work, that's a bug. In release `0.11.5-M1` I added a fix for this, could you please try whether this works for you ?

thanks ...

**Comment by sverhagen** [comment]
Thank you for that. I feel you're explaining to me why the two scenarios are different and thus why what I experience isn't a bug. So, what then did you fix? (Happy to test if I understand it...)

**Comment by rhuss** [comment]
You said that the first variant doesn't work for you, but it should. Or otherwise: What doesn't work for you in the first scenario ;-) ? But maybe I misunderstood the "_the former not leading to the right result (for me)._" (if this only for the URLs then, yes, the difference is expected. If something other is wrong we should have a look at it)

**Comment by sverhagen** [comment]
Combined with issue #169 I'm no longer sure how I tested this to break in the first place. It seems to work in before *and* after, so not being very helpful here.

While testing this I had to go from 0.11.5-M1 to 0.11.5-SNAPSHOT (SHA1: 3f81bca7d349af3a6d0c597816b8ce702afbfe3e). The 0.11.5-M1 gave me the following:

    [INFO] --- docker-maven-plugin:0.11.5-M1:start (pre-test) @ myProject ---
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 8.372 s
    [INFO] Finished at: 2015-05-21T01:07:41-07:00
    [INFO] Final Memory: 34M/482M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.5-M1:start (pre-test) on project myProject: Execution pre-test of goal org.jolokia:docker-maven-plugin:0.11.5-M1:start failed: Image name must not be null -> [Help 1]

I'm happy to file an issue, if necessary.

**Comment by rhuss** [comment]
I've found this, it should be fixed now (was a silly bug from myside).

If you don't mind I close this ticket. Feel free to reopen it in case or if the error above occurs again, too.

**Comment by sverhagen** [comment]
Could you tell me how/where `Image name must not be null` got fixed?

**Comment by rhuss** [comment]
I fixed it [here](https://github.com/rhuss/docker-maven-plugin/commit/22acd5684dcd7c305067aca6695c83c4108197e9#diff-704fe248f33f9e2640ed300367bee453L367) which I introduced since 0.11.5-M1. So I'm pretty sure that this fix your isuee. If not, feel free to open a ticket and please provide the full stack trace then. Thanx.

**Comment by rhuss** [comment]
And apologies that I didn't mentioned this in the commit log (or made a separate commit).
