### ISSUE TITLE
Run containers in non-daemon mode

### ISSUE THREAD

**Issue by arun-gupta** [rhuss/docker-maven-plugin#176]
Currently there is no way to run the container in a non-daemon mode. Need an equivalent of something like:

```
docker run -it -p 8080:8080 arungupta/wildfly
```

**Comment by rhuss** [comment]
Added a parameter `-Ddocker.follow` which wait forever to finish (similar to `-i`) but does no watch. Also, the log will be shown by default but can be switched of with `-Ddocker.showLogs=false`
