### ISSUE TITLE
cannot docker:remove

### ISSUE THREAD

**Issue by jufis** [rhuss/docker-maven-plugin#178]
Is there a way to pass -f when docker:remove runs?

>mvn -Ddocker.image=registry.jufis.net:443/jufis-dev/docker-rest-server:latest -Ddocker.removeAll clean docker:remove

<pre>
[ERROR] DOCKER> Conflict, cannot delete 5a45a0e0111c because the container 3feabe04b961 is using it, use -f to force (Conflict: 409)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.309 s
[INFO] Finished at: 2015-05-22T02:32:15+03:00
[INFO] Final Memory: 17M/297M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.4:remove (remove) on project docker-rest-server: Unable to remove image [registry.jufis.net:443/jufis-dev/docker-rest-server:latest] -> [Help 1]
</pre>

Cheers!

**Comment by rhuss** [comment]
By default 'force' is always applied, but there is a bug which prevent this ;). This will be fixed in 0.11.5.
