### ISSUE TITLE
Support RUN Command definition, through plugin configuration

### ISSUE THREAD

**Issue by javapapo** [rhuss/docker-maven-plugin#191]
I would like to be able, to define one or more *'RUN'* commands, when defining my `<image>`  element. For example, in a case where I want to execute some jboss-cli script(s), I would like to have something like
```
<image>
        <alias>myService</alias>
                 <name>AName</name>
                             <build>
                                    <from>jboss/wildfly</from>
                                      <maintainer>javapapo@mac.com</maintainer>
                                       <assembly>
                                           <descriptor>assembly.xml</descriptor>
                                           <basedir>/opt/jboss/wildfly/standalone/deployments</basedir>
                                        </assembly>
                                        <ports>
                                            <port>8080</port>
                                            <port>9090</port>
                                        </ports>
                                    <runCommands>
                                      <runcmd>echo "Hello World"</runcmd>
                                       <runcmd>/opt/jboss/wildfly/bin/add-user.sh admin pass --silent</runcmd>
                              </runCommands>
       </build> 
... 
```
and in the generated dockerFile would look like.
```
FROM jboss/wildfly
MAINTAINER javapapo@mac.com
EXPOSE 8080 9090
RUN echo "Hello World"
RUN /opt/jboss/wildfly/bin/add-user.sh admin pass --silent
```

Many thanks for considering.

**Comment by rhuss** [comment]
Good point, shouldn't be hard to add (start at `DockerFileBuilder`). Are you on a PR ? If not, I can implement this (after integrating some other stuff first).

**Comment by javapapo** [comment]
I will give a try, yes I pulled master just yesterday!

**Comment by tnn** [comment]
:+1: Would be great with a `RUN` command.

**Comment by rhuss** [comment]
The question of course is still, where to place the RUN commands: Before or after the ADD commands ? Probably after.

**Comment by javapapo** [comment]
Hi, I have hacked an example most probably will push to tomorrow, where I have the runCommands section after the ports section config. I need to see where you support ADD in the configuration

**Comment by computerlyrik** [comment]
+1 ... need some code review on your code?

**Comment by computerlyrik** [comment]
Tested your code. Lacks some features from origin master.
I will try a merge tomorrow.

**Comment by computerlyrik** [comment]
Merged :+1:

**Comment by javapapo** [comment]
Hello, sorry due to some work obligations I did not repost here - since I had not fully tested the change.

**Comment by javapapo** [comment]
my feature is under feature/runCmds branch

**Comment by computerlyrik** [comment]
@javapapo my pull request is about your code with a little modifications

Hopefully it gets accepted :)

**Comment by rhuss** [comment]
Thanks a lot, guys  ! I will have a look at is ASAP and will integrate it ...

**Comment by javapapo** [comment]
@computerlyrik  thanks great! Still think maybe we should add a bit of more checks on the parsing of the command, will wait @rhuss  comments :)
