### ISSUE TITLE
allow 'extraHosts' to accept hostname as destination ip

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#196]
this is similar to #101.

i want to specify a hostname as the destination address in the maven configuration that will be resolved to an ip address at runtime, eg:
```xml
<run>
  <extraHosts>
    <host>dev-db.hostname.pvt:docker-dev.hostname.pvt</host>
  </extraHosts>
</run>
```
this lets me inject the correct ip address by way of `/etc/hosts` instead of using maven properties. 

if the specified host cannot be resolved at start time, the plugin will throw an error.

**Comment by rhuss** [comment]
If I understand right, you want in you example `docker-dev.hostname.url` to be looked up by the plugin before handing it over to Docker as `extraHosts`.

Looks good to me.

**Comment by rlingaku** [comment]
@rhuss I am using the hostname of a running container instead of its IP. But I am getting the following error
`unable to resolve ip address for <container-hostname>: Unknown host <container-hostname>: Name or service not known`

Am I missing anything!!!


`                                <image>
                                    <name>docker.io/rabbitmq:${docker.rabbitmq.version}</name>
                                    <alias>rabbitmq-az1</alias>
                                    <run>
                                        <namingStrategy>alias</namingStrategy>
                                        <hostname>rabbitmq-az1</hostname>
                                        <ports>
                                            <port>15673:15672</port>
                                        </ports>
                                        <wait>
                                            <time>30000</time>
                                            <log>Server startup complete*</log>
                                            <exec>
                                                <postStart>rabbitmq-plugins enable rabbitmq_management</postStart>
                                            </exec>
                                        </wait>
                                    </run>
                                </image>`


`<image>
                                    <name>${docker-organization-name}/pulse-az1:${project.version}</name>
                                    <alias>pulse-az1</alias>
                                    <run>
                                        <namingStrategy>alias</namingStrategy>
                                        <hostname>pulse-az1</hostname>
                                        <extraHosts>
                                            <extraHost>rabbitmq:rabbitmq-az1</extraHost>
                                        </extraHosts>
                                        <ports>
                                            <port>8081:8080</port>
                                        </ports>
                                        <env>
                                            <SOH_LOGLEVEL>ALL</SOH_LOGLEVEL>
                                        </env>
                                        <links>
                                            <link>rabbitmq-az1</link>
                                        </links>
                                        <wait>
                                            <time>600000</time>
                                            <log>transitioning from STARTING to STARTED</log>
                                        </wait>
                                        <log>
                                            <prefix>PULSE-AZ1</prefix>
                                            <date>default</date>
                                            <color>blue</color>
                                        </log>
                                    </run>
                                </image>`

**Comment by rhuss** [comment]
Could you add a `<dependsOn>` as described here --> https://dmp.fabric8.io/#start-depends-on ?

Does this help ?

**Comment by rlingaku** [comment]
@rhuss I tried with `<dependsOn>`, but I still get the same error
