### ISSUE TITLE
mvn clean package docker:build failing

### ISSUE THREAD

**Issue by samaddico** [rhuss/docker-maven-plugin#206]
Hello 

so I tried this to generate docker image of a microservice i am working .

I followed this https://github.com/spotify/docker-maven-plugin

      <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.2.11</version>
                <configuration>
                    <imageName>nurs-template-engine</imageName>
                    <baseImage>java</baseImage>
                    <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
                     
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                </configuration>
            </plugin>

But i keep having this error.

--- docker-maven-plugin:0.2.11:build (default-cli) @ template-engine ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Copying /home/dreamadmin/NetBeansProjects/nurs/template-engine/target/template-engine-1.0-SNAPSHOT.jar -> /home/dreamadmin/NetBeansProjects/nurs/template-engine/target/docker/template-engine-1.0-SNAPSHOT.jar
[INFO] Building image nurs-template-engine
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Jun 26, 2015 5:36:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.777s
[INFO] Finished at: Fri Jun 26 17:36:37 WAT 2015
[INFO] Final Memory: 18M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.11:build (default-cli) on project template-engine: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Permission denied -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Any suggestion help please.

**Comment by rhuss** [comment]
Could it be that you opened the issue for the wrong docker-maven-plugin ? There are more than one ;-)

But feel free to try mine as well ;-)

**Comment by juliangamble** [comment]
There are some insights here: https://github.com/spotify/docker-maven-plugin/issues/105

**Comment by mootezbessifi** [comment]
any response for this issue. what was causing permission denied issue ?
