### ISSUE TITLE
 no such file or directory

### ISSUE THREAD

**Issue by samaddico** [rhuss/docker-maven-plugin#213]
<plugin>
                <groupId>org.jolokia</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.12.0</version>
                <configuration>
                    <images>
                        <image>
                            <name>template:1.0</name>
                            <build>
                                <from>java:8</from>
                                
                                <tags>
                                    <tag>latest</tag>
                                    <tag>${project.version}</tag>
                                </tags>
                                <ports>
                                    <port>8064</port>
                                </ports>
                                <entryPoint>
                                    <exec>
                                        <arg>java</arg>
                                        <arg>-jar</arg>
                                        <arg>/${project.build.finalName}.jar</arg>
                                    </exec>
                                </entryPoint>
                                <assembly>
                                   
                                    <basedir>${project.build.directory}</basedir>
 
                                </assembly>
                            </build>      
                        </image>  
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>start</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>build</goal>                           
                        </goals>
                    </execution>
                    <execution>
                        <id>stop</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

Above is my setup,I just wnan generate a docker image.

I have this error 
`DOCKER> Error building image: maven: no such file or directory`
`DOCKER> maven: no such file or directory`

Any explanation to this please.

**Comment by jgangemi** [comment]
your assembly configuration is incorrect. you need to either provide an assembly descriptor or one of the predefined descriptor refs. 

`basedir` applies to the base directory inside the image. if you want to place the jar in `/`, then set `<basedir>/</basedir>`, otherwise change `<arg>/${project.build.finalName}.jar</arg>` to `<arg>/maven/${project.build.finalName}.jar</arg>`

**Comment by samaddico** [comment]
Thanks,It did work

**Comment by jgangemi** [comment]
closing
