### ISSUE TITLE
<runCmd> errors on 0.13.2

### ISSUE THREAD

**Issue by computerlyrik** [rhuss/docker-maven-plugin#222]
Hey!

I have a issue, that my runCmd Command does not execute well on newly released version.
I do have a workdir configured...but i am not 100% sure, that this is the reason.

I do simply get a "non zero state" from the execution.

How do i debug (eg printout the Dockerfile used for <build>)?

Thanks

**Comment by rhuss** [comment]
I applied your fix (since currently I don't really mind the order of WORKDIR and RUN), but I'm curious about the error message. You say "non zero state". Do you have chance to provide the output of the error message since I believe it should be more specific, too (not only for this error)
