### ISSUE TITLE
Dockerfile RUN (Short Question)

### ISSUE THREAD

**Issue by wThomas84** [rhuss/docker-maven-plugin#234]
Hi,

how can I achieve at image definition to have sth similar to the RUN directive as in the plain old Dockerfile? - Sth like: `RUN sudo chown newOwner /home/aFile`

Adding <command> tags after my <assembly> tags doesn't seem to work.

Thanks in advance.
Tom

**Comment by rhuss** [comment]
With 0.13.2 you can add `<run>` elements to the assembly description which translates to `RUN` directives in the Dockerfile. Please refer to the reference manual for the exact syntax.

What do you mean with 'adding tags after my tags' ? Can you given an example ?

**Comment by wThomas84** [comment]
Hi, thanks for the answer;
Sorry, I already had a beer that evening; It should mean "Adding run tags after my assembly tag doesn't seem to work".

However, I still used an old version, upgraded to 0.13.2 and now it works. Had to use the following config:

```
<build>
<!--...-->
    </assembly>
    <runCmds>
         <run>sudo chown newOwner /aFile</run>
         <run>./anotherScript.sh</run>
    </runCmds>
</build>
```

**Comment by rhuss** [comment]
Ah, cool. BTW, I just checked your first comment and you indeed added `<command>` and `<assembly>`, but without escapes (so GitHub interprets this as HTML tags)

So, it was was not the beer ;-)
