### ISSUE TITLE
log docker build output

### ISSUE THREAD

**Issue by rgbj** [rhuss/docker-maven-plugin#246]
Hi,

I am quite sure I am missing something, but for the life of me I can't seem to find how to get the plugin to log the output of the docker build step. Right now if my build doesn't behave the way I wish it would, I am quite in the dark as to why a build failed or didn't behave as expected. That makes debugging/tuning images builds quite painful.

So, if it's not already there and I somehow missed it, would it be possible to add output logging for the docker build step?

TIA

**Comment by rhuss** [comment]
Try '-Ddocker.verbose=true` .... (you can add `verbose` also to the top level config)

**Comment by rgbj** [comment]
there it is! Thank you, and sorry for the noise.
