### ISSUE TITLE
Specifying environment variable in java opts..

### ISSUE THREAD

**Issue by fastmap22** [rhuss/docker-maven-plugin#247]
Using version 0.13.2

I have something like this...
...
<build>
  ..
 <cmd>
      <shell>
             java -DmyVar=${MY_VALUE} -jar /opt/myApp/${project.artifactId}-${project.version}.jar
       </shell>
 </cmd>
</build>

I have this value in an external file.. /opt/myApp/data

cat /opt/myApp/data

MY_VALUE=abc

If I specify

<run>
   <envPropertyFile>/opt/myApp/data</envPropertyFile>
</run>

does not seem to work.. Are there any examples of this use case?

**Comment by rhuss** [comment]
@fastmap22 does it work for you now or is there anything I can help you ? (late to the show, I know. sorry ....)

**Comment by fastmap22** [comment]
Works for me. Thanks
