### ISSUE TITLE
Create a .classpath file in buildDir

### ISSUE THREAD

**Issue by rhuss** [rhuss/docker-maven-plugin#257]
Add a configuration option e.g. `classpathFile` which, when set creates a file in the `buildDir` with the current Maven classpath used for unit test and compilation. That way a image startup script can decide the order of the elements it wants to add to the classpath when running a jar file.

**Comment by jgangemi** [comment]
just in case you weren't aware, the `maven-dependency-plugin` offers this functionality as a goal, `build-classpath`, so perhaps there is something that could be leveraged for this.

**Comment by rhuss** [comment]
good point, thanks for the hint. Shouldn't be that big deal since there is a `MavenProject.getRuntimeClasspathElements()`. 

It was pointed out on #fabric8 at freenode (btw, you can find me there most of the time), that this might be very useful for startup scripts.

**Comment by jgangemi** [comment]
i concur - i had to so something similar to run a spark job locally and being able to pull things out of the classpath helped.

**Comment by rhuss** [comment]
Just played around with that and I believe now, this shouldn't be the task of this plugin. One could always refer to a generated file within `target/` from the assembly descriptor, so your idea of using `dependency:build-classpath` for generating this file is the better option. 

I close that issue for now.
