### ISSUE TITLE
Better handling of private registries

### ISSUE THREAD

**Issue by jstrachan** [rhuss/docker-maven-plugin#26]
sometimes folks wanna build stuff and push to the global registry; sometimes folks wanna push to a local registry. I wonder if the registry host should default to using an environment variable rather than a maven build property; as its kind of an environment thing?

e.g. I found we had to add these instructions to add a custom profile to ~/.m2/settings/xml to enable the 'default to env var' behaviour. I figured it might be nice to have this by default?
http://fabric8.io/v2/mavenPlugin.html#specifying-the-location-of-your-local-docker-registry

e.g. if a build is intended to use a private docker registry then maybe its better to get this from an environment variable?

**Comment by rhuss** [comment]
DOCKER_REGISTRY is now used as a fallback in 0.11.1 and later, so it should be safe. I'll close that one, please feel free to reopen it if it shouldn't work as expected (and described in the manual).
