### ISSUE TITLE
Q: can your run commit before shutting down container?

### ISSUE THREAD

**Issue by tszpinda** [rhuss/docker-maven-plugin#267]
Hi, is there a way to commit changes in container before shutting down container, this would be useful in multiple module projects when first sets a container up and rest just start from known state.

Cheers

**Comment by mgurov** [comment]
How different is this from building an image into the known state and then starting the image?

**Comment by tszpinda** [comment]
it would be less changes to our code I guess :) 

At the moment, we start docker db image (with empty db), then next project applies sql on top of fresh db creates schema/tables etc and this would be good point to commit the changes.

**Comment by paulwilton** [comment]
i think this is a valid use-case - 
eg : 
build a container for a database/datastore, run container, apply a schema, test, then commit, then push to registry

**Comment by af6140** [comment]
Related to #787
