### ISSUE TITLE
docker-maven-plugin:0.13.3:build for parameter ports: Cannot find 'ports'

### ISSUE THREAD

**Issue by yakhyadabo** [rhuss/docker-maven-plugin#271]
Hi everybody, 

I'm trying to run integration tests with docker-maven-plugin. I have just started using the example you have given in github. 

Here's the output when I run maven

Failed to execute goal org.jolokia:docker-maven-plugin:0.13.3:build (docker:build) on project aq-forecast-loader: Unable to parse configuration of mojo org.jolokia:docker-maven-plugin:0.13.3:build for parameter ports: Cannot find 'ports' in class org.jolokia.docker.maven.config.ImageConfiguration -> [Help 1]

The details of my environment : 
- java 8
- maven 3.3.3
- docker-maven-plugin 0.13.3 

Do you have any idea for this issue ?

**Comment by jgangemi** [comment]
can you please post your pom?

**Comment by yakhyadabo** [comment]
Here's the pom : 

---
<profiles>
		<profile>
			<id>docker</id>
			<build>
				<plugins>

					<plugin>
						<groupId>org.jolokia</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<version>0.13.3</version>
						<configuration>
							<images>
								<image>
									<alias>web-app</alias>
									<name>web-app:${project.version}</name>
									<build>
										<tags>
											<tag>latest</tag>
											<tag>${project.version}</tag>
										</tags>
										<assembly>
											<dockerFileDir>.</dockerFileDir>
											<descriptor>assembly.xml</descriptor>
											<basedir>/opt/jboss/wildfly/standalone/deployments/</basedir>
											<user>jboss:jboss:jboss</user>
										</assembly>
										<ports>
											<port>8080</port>
										</ports>
									</build>
									<run>
										<ports>
											<port>web-app.port:8080</port>
										</ports>
										<links>
											<link>database:db</link>
											<link>broker:broker</link>
										</links>
									</run>
								</image>

								<image>
									<alias>database</alias>
									<name>postgres:9.4</name>
									<run>
										
										<wait>
											<log>database system is ready to accept connections</log>
											<time>20000</time>
										</wait>
									</run>
								</image>

								<image>
									<alias>broker</alias>
									<name>hornetq:1.0</name>
								</image>
								<run>
									<ports>
										<port>broker.port:5445</port>
									</ports>
								</run>
							</images>

						</configuration>

						<executions>
							<execution>
								<id>docker:build</id>
								<phase>package</phase>
								<goals>
									<goal>build</goal>
								</goals>
							</execution>
							<execution>
								<id>docker:start</id>
								<phase>install</phase>
								<goals>
									<goal>start</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

**Comment by jgangemi** [comment]
the last image in your configuration is incorrect - you have the `run` block defined outside of the `image` block.

**Comment by yakhyadabo** [comment]
Thanks very much.

**Comment by yakhyadabo** [comment]
You can close if you want
