### ISSUE TITLE
Add a parameter to configure the number of seconds to wait before killing the container

### ISSUE THREAD

**Issue by fiji-flo** [rhuss/docker-maven-plugin#293]
I would like to expose the **t** parameter of the stop call (see https://docs.docker.com/reference/api/docker_remote_api_v1.20/#stop-a-container) to the docker-maven-plugin configuration.

This defaults to 0 in docker. Therefore, for the process running inside there is no change of a proper shutdown, when receiving SIGTERM.

In my use case the process writes some log data, when SIGTERM is received before exiting gracefully.

With the current docker-maven-plugin this file is empty.

I extended docker-maven-plugin in a fork and it is working fine there.

**Comment by rhuss** [comment]
Fixed with merge of #294
