### ISSUE TITLE
[Question]How plugin keep reference on containers?

### ISSUE THREAD

**Issue by ginbalin** [rhuss/docker-maven-plugin#303]
I was wondering how does the plugin know which container to stop?
When you launch mvn docker:start then later on mvn docker:stop, how the plugin select the container_id for the stop command?

Is it working the same way during a full build process having start goal plugged on pre-integration-test and stop goal on post-integration-test?

Thank you for your help.

**Comment by jgangemi** [comment]
right now it works against the name of the image and not the id of the container however that means if you have another container running that shares the same image name, the plugin will stop that as well. 

there is an open issue - #87 -  to address this and i am going to be finishing off the work for this very soon.

everything should work the same way regardless of if it's called from as part of the integration tests phases or as standalone maven commands.

**Comment by ginbalin** [comment]
I didn't understand exactly could you explain me with more details what is the planned implementation design?

**Comment by jgangemi** [comment]
implementation design for what?

**Comment by ginbalin** [comment]
For this issue #87 
What is the solution you will implement?

**Comment by jgangemi** [comment]
we will be adding labels to tie things together.

**Comment by ginbalin** [comment]
Oki got it. Thanks I'm waiting for it.
Cheers

**Comment by jgangemi** [comment]
as a work around, you could build a new image (or create a custom tag) and only refer to that tag in the specific project.

**Comment by ginbalin** [comment]
Yeah could do that.
Also would it be easy to add a feature so that you can set the container I'd you want to stop as a command parameter e.g.
Men docker:stop -Dcontainerid ehdjdirhsk

**Comment by jgangemi** [comment]
yeah - i believe that feature has been requested before as well. once the label tracking is implemented i don't think being able to specify a container id will be necessary but we can see when the time comes.
