### ISSUE TITLE
Add port wait condition

### ISSUE THREAD

**Issue by svenwltr** [rhuss/docker-maven-plugin#304]
An additional wait condition, which waits for specific ports, would be useful. The configuration could look like this:

```xml
<wait>
  <port>
    <tcp>3306</tcp>
    <pollIntervall>500</pollIntervall>
    <pollLimit>20</pollLimit>
  </port>
</wait>
```

I want to work on this and make a pull request and I am interested in your opinions.

**Comment by rhuss** [comment]
You mean waiting on this exposed docker-host exposed port, right ? Mostly these are http ports, db ports etc. are typically hidden within Docker links (when using multiple  images). 

I'm curious what's your concrete use case is for this feature ?

**Comment by svenwltr** [comment]
The use case is a service, which is watching database changes and broadcast them to a message queue. This means, on an integration test, we add entries to an database and check generated message queue output. Therefore, we need direct access to the database and the message queue service.

**Comment by rhuss** [comment]
I see your point and think it would be a good addition. Configurationwise, maybe we could bring it on the same level as `<http>` ? For example:

```xml
<tcp>
    <port>3306</port>
    <host>blub.com</host>  <!-- optional, default ${docker.host.address} --> 
    <interval>500</interval> <!-- optional, default: 500ms -->
</tcp>
```

I  would leave out `<pollLimit>` since we already have a timeout. However I wonder whether there's a use case for udp, too  ? (because then we would have to replicate this configuration)

**Comment by svenwltr** [comment]
This configuration looks good. I'll use this one.

There may be a use case for UDP for others, but not for us. Checking a UDP port differs (minimal) from TCP. So I think a replicate this configuration is a good idea for future implementations anyway.
