### ISSUE TITLE
Support for an unencrypted connection to a registry

### ISSUE THREAD

**Issue by phauer** [rhuss/docker-maven-plugin#305]
Hi,
I' running into troubles, when I use an IP in the repository name instead of "localhost". My docker registry runs on port 5000 and can be accessed either by "localhost" or by an IP. Using http://localhost:5000/ or http://192.168.35.217:5000/ (note "http", not "https") in my browser provides me access to my registry.
````xml
<plugin>
				<groupId>org.jolokia</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.13.3</version>
				<configuration>
					<images>
						<image>
							<alias>hello-world-app</alias>
							 <name>localhost:5000/hello-world-app:0.0.1-SNAPSHOT</name> 
````
This works fine. The image is pushed successfully to my local registry.
However, when I'm using an IP in the repository name like...
````xml
<name>192.168.35.217:5000/hello-world-app:0.0.1-SNAPSHOT</name> 
````
I get the following error:
````
[INFO] --- docker-maven-plugin:0.13.3:push (default-cli) @ hello-world-app ---
[INFO] DOCKER> ... The push refers to a repository [192.168.35.217:5000/hello-world-app] (len: 1)
[ERROR] DOCKER> unable to ping registry endpoint https://192.168.35.217:5000/v0/
v2 ping attempt failed with error: Get https://192.168.35.217:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://192.168.35.217:5000/v1/_ping: tls: oversized record received with length 20527
[ERROR] DOCKER> unable to ping registry endpoint https://192.168.35.217:5000/v0/
v2 ping attempt failed with error: Get https://192.168.35.217:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://192.168.35.217:5000/v1/_ping: tls: oversized record received with length 20527 
````
The problem is that the plugin tries to access the registry through an encrypted connection (httpS), which is not provided by the registry. Hence, I like to access my registry unencrypted (using http). Consequently, I would like to configure whether the connection to the registry should be encrypted or not.

Cheers Philipp

**Comment by rhuss** [comment]
The point is, that the registry is contacted through the docker daemon, but never directly by the plugin. What you must do is to configure your Docker daemon to access the docker registry unsecured with `--insecure-registry` or so.

Does this help ?

**Comment by phauer** [comment]
Hi Roland, thanks for your helpful response.
I added "--insecure-registry 192.168.35.217:5000" to my DOCKER_OPS in /etc/default/docker and after a restart the push succeeds. However, I guess it's the best to configure my registry to support encrypted connections, because configuring every docker daemon that wants to access the registry is laborious.
Again, thank you very much. This issue can be closed.

**Comment by rhuss** [comment]
Glad that I could help :)

cheers ...
