### ISSUE TITLE
Docker push multiple tags on the same image

### ISSUE THREAD

**Issue by testn** [rhuss/docker-maven-plugin#309]
How do I push more than one docker tag at the same time?

i.e.

I want to make sure that the image got tagged at latest so I would like to push

myapp:1 and myapp:latest

when I have a change, I then would like to push 

myapp:2 and myapp:latest

**Comment by rhuss** [comment]
You simply add a 

```xml
<tags>
  <tag>latest</tag>
</tags>
```

to your `<build>` configuration. Using `mvn package docker:build docker:push` then will build the image, tag it and pushes both images.

I hope this answer you question, feel free to reopen this issue if not.
