### ISSUE TITLE
How to mount volume with remote docker engine?

### ISSUE THREAD

**Issue by ginbalin** [rhuss/docker-maven-plugin#310]
Hello,

I came across this problem this week. 
I run the docker engine on my CI infrastructure which works well for automated build/test as the docker engine is installed on the build slave.
But sometimes I want to run the integration test from my developer desktop. In that case the files I want to mount in my container are on my computer but the engine is remotely accessed. And it is not possible to mount a volume in docker remotely.
Did some people had that kind of problems and how did you solve it?
Currently I just copy the file manually on the docker engine host but would you see a nice solution to integrate that in the plugin or at least in the maven process?

**Comment by rhuss** [comment]
What kind of data are you accessing ? 

What you can do in principle is to put everything what you need into a data image (also from within the plugin) and mount that as volume.  If you want a mixed mode (e.g. ci mount from directories, develop from a data container), you could use Maven profile for different d-m-p configuration setups.

**Comment by ginbalin** [comment]
I want to mount configurations of my dockerized application. (e.g. sql create tables scripts). Yeah I will check the data image solution.

**Comment by ginbalin** [comment]
Finally I used maven ant run plugin to push with scp files to the docker host.
