### ISSUE TITLE
Blocked maven phase

### ISSUE THREAD

**Issue by CyborTronik** [rhuss/docker-maven-plugin#316]
I have configured plugin with around 15 docker images.
And from to time to time all docker starts but this plugin doesn't allow to go on next maven phase even all images has been started.

Sry, I can't share configuration details as most of the docker images are private.
Is anything to do with that? 

PS: Would be nice  to have ability to trace the plugin actions for next times.

**Comment by rhuss** [comment]
Images are started in sequence, so when the last image has been started and its wait condition is fullfilled, the plugin goals continues **except** you have set the property `docker.follow` (or the global configuration `follow`) to true. In that case `docker:start` block forever until killed. 

See also [here](https://github.com/rhuss/docker-maven-plugin/blob/master/src/main/java/org/jolokia/docker/maven/StartMojo.java#L72-L104)

Is that the case for you ?

**Comment by CyborTronik** [comment]
Thank you for quick reply, it is very appreciative considering type of the project.

Just changed log text (just waiting for next log line) and is working well now. So I think I will not be able to reproduce it, so the ticket can be closed.

Thanks
