### ISSUE TITLE
Support settings docker name?

### ISSUE THREAD

**Issue by khong07** [rhuss/docker-maven-plugin#319]
Hi,

I don't found the option in run section allowing to set the docker container name. It's not supported or I'm missing something :) I want to set the container name manually (to distinguish the container created by the plugin and those created by another process)

Thank you!

**Comment by jgangemi** [comment]
this is already possible by setting an `alias` for the container and changing `namingStrategy` to `alias`.

see http://ro14nd.de/docker-maven-plugin/docker-start.html.

**Comment by khong07** [comment]
Hi,

Yes, I forgot that I can use alias in image configuration :+1: thank you
