### ISSUE TITLE
Dynamic host property in port mapping is not filled in if port is specified

### ISSUE THREAD

**Issue by caspark** [rhuss/docker-maven-plugin#323]
I have a port mapping config like the following:

```
<run>
    <ports>
        <port>+docker.ondemand.postgres.host:docker.ondemand.postgres.port:5432</port>
    </ports>
</run>
```

Ordinarily, I can access `${docker.ondemand.postgres.host}` & `${docker.ondemand.postgres.port}` after the docker container has started.

But if I specify `-Ddocker.ondemand.postgres.port=5432` then `docker.ondemand.postgres.host` is not dynamically set.

This appears to be because of the following snippet in `org.jolokia.docker.maven.service.RunService#createAndStartContainer`

        if (mappedPorts.containsDynamicPorts()) {
            updateMappedPorts(id, mappedPorts);
        }

Changing it to

        if (mappedPorts.containsDynamicPorts() || mappedPorts.containsDynamicHostIps()) {
            updateMappedPorts(id, mappedPorts);
        }

seems to fix this bug, so I'll raise a PR for this.

**Comment by joschi** [comment]
+1, I also ran into this issue lately.

**Comment by rhuss** [comment]
Thanks, PR applied for 0.13.7
