### ISSUE TITLE
change required maven version

### ISSUE THREAD

**Issue by computerlyrik** [rhuss/docker-maven-plugin#329]
Do we need a pinnng to 3.2.1 in https://github.com/rhuss/docker-maven-plugin/blob/master/pom.xml

Or is it okay to go with 3.2.*?

**Comment by jgangemi** [comment]
that just means `3.2.1` is the minimum version of maven required for the plugin. anything newer then that is fine to use.

**Comment by rhuss** [comment]
@computerlyrik does this answer your question ? 

In fact I'm not really sure what 'advanced' Maven features we are using, have to check and document this, too.

**Comment by computerlyrik** [comment]
Tnx. Works with 3.2.5 for me.

Perhaps s/o should file a feature request to name the maven tag more explicitly (minVersion or sth)
