### ISSUE TITLE
can i get nexus access?

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#332]
it would be super helpful if i was able to push snapshots to the `d-m-p` repository instead of having to muck around w/ my own. would that be ok by you? i can add some kind of identifier to indicate i pushed.

my oss nexus username is my email if you're ok w/ this.

thanks! :)

**Comment by rhuss** [comment]
You are welcome :) Just opened an JIRA ticket to add you as deployer, might take a bit ...

**Comment by rhuss** [comment]
Just got notice that you have the permissions now. Feel free to publish snapshots as you like, for releases please let us negotiate before. (Especially because I have the GPG key ;-)

I'll close this issue, if it doesn't work, please reopen.

**Comment by jgangemi** [comment]
cool - i'm only interested in pushing snapshots, releases will still be left to you. i just tried pushing `0.13.7-jae-test-SNAPSHOT` and it worked. 

thanks again!
