### ISSUE TITLE
Risk for large Image Layer due to chown

### ISSUE THREAD

**Issue by Khazrak** [rhuss/docker-maven-plugin#336]
If the base directory for you assembly contains files and you use <user> in <assembly> then it will chown -R the whole directory. So if you have a server in that directory and the assembly just copies in config then the whole server-directory will be chown:ed. This means that all the files have been changed in that Image Layer and is added to the Image size.

Don't know if this will be optimized or not, but it's probably good for users to know.

The only solution I can think of is copying the files to /tmp/folder, chown -R that folder and then move it to the target destination

**Comment by rhuss** [comment]
Completely agreed that there is a gotcha when not using an empty directory as `basedir`. I implemented your suggestion for 0.13.7

Just to be sure: That happens for you when you are using a `<user>` in the assembly configuration, right ?
