### ISSUE TITLE
Dockerize generic Spring boot app with maven plugin

### ISSUE THREAD

**Issue by computerlyrik** [rhuss/docker-maven-plugin#339]
Hi! 
I did some testing but cannot achive the following:

A Spring Boot app consists only of a runnable Jar. So the Dockerfile as suggested by Spring itself as follows:

```
FROM java:8
VOLUME /tmp
ADD gs-spring-boot-docker-0.1.0.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

I want to transform this into ```<build></build>``` to **get rid of the Dockerfile* and make use of the many nice maven properties.

Now, i am still hanging on putting the resulting ```artifact-0.0.1-SNAPSHOT.jar``` as ```app.jar``` to the docker container.

S/o got any help? How do i configure my assembly?

Yes, i read http://ro14nd.de/docker-maven-plugin/docker-build.html but i do not understand the handling of assemblyDescriptorRef and such.

**Comment by rhuss** [comment]
Try something like this in the build configuration:

```xml
<build>
  <from>${image}</from>
  <assembly>
    <basedir>/</basedir>
    <inline>
      <id>spring-boot-jar</id>
      <dependencySets>
        <dependencySet>
          <useProjectArtifact>true</useProjectArtifact>
          <includes>
            <include>mygroup:app</include>
          </includes>
          <outputDirectory>.</outputDirectory>
          <outputFileNameMapping>app.jar</outputFileNameMapping>
        </dependencySet>
      </dependencySets>
    </inline>
  </assembly>
</build>
```

Note the `outputFileNameMapping` config. For assemblies you can everything as described for the [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html)

`basedir` puts it into `/` into your image (by default this is `/maven`).

BTW, soon we will extend direct Dockerfile support with placeholders, also for an assembly so things might get even easier.

**Comment by computerlyrik** [comment]
@rhuss  Thanks a lot for the fast answer.

I am getting the following error:
```
 Failed to execute goal org.jolokia:docker-maven-plugin:0.13.6:build (build-image) on project myproject: Failed to create assembly for docker image: Error adding file 'de.computerlyrik.mygroup:myproject:jar:0.0.1-SNAPSHOT' to archive: /home/cf/projects/myproject/target/classes isn't a file. with mode dir -> [Help 1]
```

With the following config

```xml
							<build>
								<from>java:8</from>
								<assembly>
									<basedir>/</basedir>
									<inline>
										<id>spring-boot-jar</id>
										<dependencySets>
											<dependencySet>
												<useProjectArtifact>true</useProjectArtifact>
												<includes>
													<include>${project.groupId}:${project.artifactId}</include>
												</includes>
												<outputDirectory>.</outputDirectory>
												<outputFileNameMapping>app.jar</outputFileNameMapping>
											</dependencySet>
										</dependencySets>
									</inline>
								</assembly>
							</build>
```

**Comment by computerlyrik** [comment]
Btw i am running ```mvn clean package docker:build```

**Comment by computerlyrik** [comment]
Okay. Fail detection complete.

Do NEVER run the docker:build target on compile time :/

Thanks, this above example works!
