### ISSUE TITLE
Expose extra volumes on build after runCmds

### ISSUE THREAD

**Issue by ByteFlinger** [rhuss/docker-maven-plugin#341]
I am trying to export a few different paths in a volume container built by the plugin by setting up the assembly with all the files I need and then trying to run commands using runCmds tag to move files into folder which I expose as volumes using the <volumes> tag.

This does not seem to work as I get empty directories in the folders I exposed as volumes. I believe this has to do with the fact that the copy command happens after all volumes have been exposed

It's stated clearly in the Dockerile VOLUME documentation

>Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

Wouldn't it be better to export extra volumes after all runCmds have run?

**Comment by rhuss** [comment]
Missed that, thanks for pointing that out. Moved it now to the end of the Dockerfile, this will be available in 0.13.7, to be released this week ...

**Comment by ByteFlinger** [comment]
Wow, that was quick.
Awesome. I originally meant the bug report for the volumes tag but I
realise even the assembly tag created volume can probably be moved to the
end as well, keeping all volumes at the same place.

Looking forward to the release.

**Comment by rhuss** [comment]
Well, it's not always that fast ;-) (but currently I'm working on a release anyway :)
