### ISSUE TITLE
Update config file (persistence.xml) with docker dynamic port

### ISSUE THREAD

**Issue by heapifyman** [rhuss/docker-maven-plugin#343]
Hello,

I'm trying to run tests for an application using hibernate JPA against a database inside a docker container.
So my db connection is defined inside a persistence.xml.

Now I would like to use the dynamic port allocated when the container is started, like so:
```
<ports>
    <port>db.port:3306</port>
</ports>
```

But the problem is that the property "db.port" will only be updated with the dynamic port once the container has started (pre-integration-test), right? Which is after persistence.xml has been packaged into the war file.

Did I misunderstand something or maybe missed a configuration option that would solve this problem?
Should I bind docker:start to an earlier phase? But then I would end up with started containers which would have to be shut down manually, in cases where I only run maven goals which are after docker:start but before integration tests?

Not sure if this is the right place to ask such questions. If it is not, please point me to the right place.

Thanks in advance.

**Comment by jgangemi** [comment]
you need to change your tests to be able to accept the port as a system property and then alter your `failsafe` configuration to pass `db.port` as system property to your test.

**Comment by jgangemi** [comment]
you could also use the `portPropertyFile` setting and have the props written to a file that you could load in your test.

**Comment by heapifyman** [comment]
If I understand correctly, the first option would only work when actually running integration tests?
The db.port property would not be available when e.g.
1. running mvn docker:start
2. "manually" running/debugging a test from the IDE

It would also not work in situations where I don't actually have control over creating the EntityManagerFactory (connection to the DB), e.g. when deploying a war and datasource to a Java EE server?

In the second option: I assume the portPropertyFile is written whenever docker:start succeeds?

**Comment by jgangemi** [comment]
well - if you want to run the test from an ide, start the container via `docker:start`, run a `docker ps` command to get the port it's been mapped to and then inside your test runner in the ide, set a system property your tests knows to ready that has the port you just got from `docker ps`.

if you start the applications server via a maven plugin, as long as your app can pull values from system properties, it will work. if you are starting an external tomcat server, then no, it won't and the `portPropertyFile` option would be better suited to your needs.

it gets written upon successful startup of the container(s). you have the ability to set a global value that all containers will write to or you can set a property file for each container you start.

**Comment by heapifyman** [comment]
Ok thanks. I will give the ```portPropertyFile``` a try then.

**Comment by heapifyman** [comment]
```portPropertyFile``` seems to be working fine. Thanks
