### ISSUE TITLE
Use ~/.kube/config for getting authentication information

### ISSUE THREAD

**Issue by rhuss** [rhuss/docker-maven-plugin#350]
Add a dedicated property like `docker.kubernetesAuth` which does the following when enabled:

* Read `~/.kube/config` as YAML file
* Look for the default context (i.e. the active context)
* Lookup the corresponding server and the credentials
* Use user, password, email for authentication against a docker registry

**Comment by rhuss** [comment]
This is a followup story to #147

**Comment by jgangemi** [comment]
fyi: i am using snakeyaml to handle #57...just in case you decide to tackle this before i get my PR in.

**Comment by rhuss** [comment]
thanks for the heads up, we hereby settle on snakeyaml as the library for parsing yaml ;-)
