### ISSUE TITLE
Problem with the log stream

### ISSUE THREAD

**Issue by sebastiankirsch** [rhuss/docker-maven-plugin#354]
We have the problem that when starting our application with docker:start, the log stream is usually incomplete or randomly fails to parse some data like

    Invalid log format for '�2015-12-09T14:39:45.6445' (expected: "<timestamp> <txt>")

or 

    Invalid log format for '�2015-12-09T14:53:15.738164970Z 2015-12-09 14:53:15,737 INFO  d.i.c.i.c.ResourceServerConfiguration - enable OAuth2 resource server �201' (expected: "<timestamp> <txt>")

and then seizes to transfer the output of our application.

When writing the application output to a local file (via `| tee /tmp/log`), everything is complete and those funny characters (or the timestamp) are lacking; so this seems to be related to the mechanics of the plugin.

I'm running Docker version 1.9.1, build a34a1d5 on Ubuntu 14.04LTS. A colleague of mine has the same setup and the same problems, another colleague uses Docker 1.8.1, Mac OS X 10.10.5, docker machine 0.4.1 and does not experience those problems.

Our maven configuration is

            <plugin>
                <groupId>org.jolokia</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.13.6</version>
                <configuration>
                    <logDate>default</logDate>
                    <autoPull>true</autoPull>
                    <images>
                        ...
                    </images>
                    <authConfig>
                       ...
                    </authConfig>
                </configuration>
            </plugin>

**Comment by rhuss** [comment]
Which version of the plugin are you using ? There was a fix recently for this chunked encoding issue ...

**Comment by rhuss** [comment]
See #259 for details.

**Comment by rhuss** [comment]
Ok, seems not really to be fixed, so I will pick up this. 

Let's continue at #259 since its the older issue ....
