### ISSUE TITLE
Authorization for pull from private registry - POM, Dockerfile - difference

### ISSUE THREAD

**Issue by slawekjaranowski** [rhuss/docker-maven-plugin#358]
When I use direct `Dockerfile` with 
   
    FROM loclarepository/image

authorization fail, but when I use 

    <from>loclarepository/image</from> 

in `pom` authorization is ok.

**Comment by alan-czajkowski** [comment]
i have the same problem, the plugin does not pick up the authentication inside the ```<server>``` tag in the ```~/.m2/settings.xml``` when the repo is specified in a ```Dockerfile``` in the ```FROM``` clause, but it does work when you use the ```<from>``` in ```<build>``` tag

**Comment by rhuss** [comment]
Yes, that's true since the in the plain Dockerfile mode the Dockerfile is not parsed but directly used. 

I agree that this should be considered as a bug.
