### ISSUE TITLE
Start same image with not same alias

### ISSUE THREAD

**Issue by sebglon** [rhuss/docker-maven-plugin#359]
If i want to start the same image config with a different alias, the first container is stop and and a new container is started;

Maven profilA
   Alias: Container-A
Maven profilB
   Alias: ContianerB

mvn docker:stop docker:start -P profilA
docker ps is OK i have Container-A
After this i start second profil
mvn  docker:stop docker:start -P profilB
docker ps 
Container-A is stoped and removed
and  container-B is UP

I think that docker:stop not work with alias but image.
Can you made priority to Alias if strategy=alias

**Comment by rhuss** [comment]
Correct, stopping is performed based on the image name only.

You suggestion to use the container name which is set to the alias when the naming strategy is `alias` is a good idea, so we should add it to one of the next releases.
