### ISSUE TITLE
respect settings in .dockerignore 

### ISSUE THREAD

**Issue by computerlyrik** [rhuss/docker-maven-plugin#362]
I have a ```Dockerfile``` inside my project root.

The assembly within the maven plugin is configured
```xml
								<assembly>
							<dockerFileDir>${project.basedir}</dockerFileDir>
								</assembly>
```

How do i prevent the system from including the ./target folder recursively on building?

A .dockerignore file like 
```
target/
```
Does not help.

**Comment by rhuss** [comment]
You are right, `.dockerignore` is a feature of the docker CLI command (which is not used by this plugin). 

I just added support for a `.maven-dockerignore` file which can hold [Ant style](http://ant.apache.org/manual/Types/fileset.html) patterns for excluding files. 

For advanced cases a `%regex[...]` as described [here](http://maven.apache.org/plugins/maven-assembly-plugin/advanced-descriptor-topics.html) should do it, too. But that's neither tested nor documented ;-)

'hope that fits your use case.

**Comment by rhuss** [comment]
0.13.8 released

**Comment by StevesRoger** [comment]
Where should i put .maven-dockerignore?

**Comment by mteodori** [comment]
why not just using the standard .dockerignore and invent another file doing the same?

**Comment by rhuss** [comment]
Because it uses different syntax and has different caps.

![image](https://user-images.githubusercontent.com/99080/110443369-205b6680-80bc-11eb-8565-bccad5905478.png)
