### ISSUE TITLE
Add release note/changelog

### ISSUE THREAD

**Issue by testn** [rhuss/docker-maven-plugin#363]
It would be nice to know what the changes in each release. It is easier than looking through the tagging at https://github.com/rhuss/docker-maven-plugin/issues?q=milestone%3A0.13.8

**Comment by jgangemi** [comment]
https://github.com/rhuss/docker-maven-plugin/blob/master/doc/changelog.md

**Comment by testn** [comment]
Ah thanks.. I didn't notice the link
