### ISSUE TITLE
[ERROR] DOCKER> name unknown

### ISSUE THREAD

**Issue by rodlogic** [rhuss/docker-maven-plugin#369]
I removed all my local images and tried ```mvn docker:build```. However, this time, I got an error trying to download the ```<from>tomcat:latest</from>``` image:
```
[ERROR] DOCKER> name unknown: The repository with name 'tomcat' does not exist in the registry with id '295240448163' (Internal Server Error: 500)
```

It seems that the image name ```<name>${docker.registry}/${project.artifactId}:${project.version}</name>``` is locking the registry to ```${docker.registry}``` instead of trying the main public registry.

**Comment by rhuss** [comment]
If you provide `docker.registry` as config parameter then every image without an explicit registry part is using this registry.

You have several options:

* Specify the registry as part of the name (i.e. `docker.io/tomact:latest`)
* Use `docker.registry` only for the image you need it.
* Use `docker.push.registry` and `docker.pull.registry` with different registry. I.e. if you only want to push the images to your private registry, configure `docker.push.registry`. This is new in 0.13.8, see also [my blog post](https://ro14nd.de/registry-magic-with-dmp/) on this topic.

Does this help ?

**Comment by rodlogic** [comment]
It does. I thought about adding the registry part in from of ```tomcat:latest``` but stupidly used the wrong one. I think I am all set for now as the it now works as I wanted.

For what is worth, this is indeed the best docker plugin as fas as I know. The docs are up to date and it seems complete with respect to building and pushing. Congrats for the great work here.
