### ISSUE TITLE
Docker push push image with different sha

### ISSUE THREAD

**Issue by testn** [rhuss/docker-maven-plugin#376]
It looks like there is a bug somehow but I haven't spent time looking into it. Basically, when there are multiple images with the same hierarchy pushed to the registry, the every layer seem to be uploaded every time with different id causing the image to be bloated on the server.

**Comment by rhuss** [comment]
It would be awesome if you could provide a (stripped down) example where this happens since I haven't seen this behaviour yet.

**Comment by testn** [comment]
Turned out to be a bug in Docker 1.6.1
