### ISSUE TITLE
Changing order of RUN vs COPY?

### ISSUE THREAD

**Issue by andyshinn** [rhuss/docker-maven-plugin#377]
I don't think it is currently possible to do so. But I'd like to have some of my `RUN` commands happen before the `COPY`. My use case is for package management and dependencies that don't change that often. Right now, the `COPY` happens first and invalidates the cache of those `RUN`, which causes them to be done again. Those are costly steps in terms of bandwidth and time.

I wonder if it makes sense to allow multiple `runCmds` sections and move the optimize to it as well. It could look something like:

```xml
<runCmds>
  <beforeCopy>true</beforeCopy>
  <run>apt-get -q update</run>
  <run>apt-get -qy install mypkgs</run>
  <optimise>true</optimise>
</runCmds>
<assembly>...</assembly>
<runCmds>
  <run>java -jar my.jar setupotherstuff</run>
</runCmds>
```

**Comment by jgangemi** [comment]
this might be better suited to an external `Dockerfile`, would that work for you?

**Comment by andyshinn** [comment]
Probably. I read in another issue that the assembly stuff may be working with a custom `Dockerfile` soon. Is there any examples of that currently?

**Comment by jgangemi** [comment]
could you be a little more specific or point me to that specific issue? i'm not sure what you're referencing.

**Comment by andyshinn** [comment]
Ths specific comment I was thinking of was https://github.com/rhuss/docker-maven-plugin/issues/327#issuecomment-160878652. It looks like they were referring to https://github.com/rhuss/docker-maven-plugin/issues/205 and https://github.com/rhuss/docker-maven-plugin/issues/203.

**Comment by jgangemi** [comment]
i don't think so - if you have questions on what you need to do to make the assembly work, feel free to ask.

**Comment by rhuss** [comment]
@andyshinn adding the possibility to refer to an assembly from within Dockerfile is indeed planned for one of the next versions. I'm just thinking about how this could be done best without breaking the Dockerfile syntax (to much).

**Comment by andyshinn** [comment]
OK great. I guess the combination of that + using the alternative `Dockerfile` method would solve what I want to do. Is there another issue already open for the `Dockerfile` assembly part? If so, we can just close this.

**Comment by rhuss** [comment]
Its tracked via #205, so I'll close this one for now.
