### ISSUE TITLE
creating `HostConfig` at container start deprecated by docker

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#381]
i think we still support this and if not this should be closed, but this was deprecated as of docker `1.10.0`.

https://docs.docker.com/engine/deprecated/

**Comment by rhuss** [comment]
No, I don't think that is the case anymore. All configuration is done during container `create`, with `start` only firing up the container --> https://github.com/rhuss/docker-maven-plugin/blob/782fa9364022bbcac19e9e69f344b17a94548773/src/main/java/org/jolokia/docker/maven/access/hc/DockerAccessWithHcClient.java#L169-L177
