### ISSUE TITLE
allow for logging of the build docker build steps

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#382]
right now the only way to get this is via `mvn -X` which is way to verbose, so there should be a separate option to provide parsed output at the `INFO` level.

**Comment by rhuss** [comment]
This already happens when `<verbose>` is switched on (or `docker.verbose` system property)

Is it that what you are looking for ?

**Comment by jgangemi** [comment]
maybe, let me try that

**Comment by jgangemi** [comment]
yup, awesome, sorry for the noise!
