### ISSUE TITLE
Cannot apply patch to base image

### ISSUE THREAD

**Issue by tdiesler** [rhuss/docker-maven-plugin#53]
We are using a wildfly base image with an applied patch. The Dockerfile is 

```
# Use the wildfly-8.1.0.Final image
FROM tdiesler/wildfly:8.1.0.Final

MAINTAINER Thomas Diesler <tdiesler@redhat.com>

# [TODO] Why does this not work?
# ADD wildfly-camel-patch-1.0.0.CR3-SNAPSHOT.tar.gz /opt/jboss/wildfly

# Copy & Extract the WildFly Camel patch
COPY wildfly-camel-patch-1.0.0.CR3-SNAPSHOT.tar.gz /tmp/wildfly-camel-patch.tar.gz
RUN tar -xzf /tmp/wildfly-camel-patch.tar.gz -C /opt/jboss/wildfly 

# Set the default command to run on boot
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone-camel.xml", "-b", "0.0.0.0"]
```

It seems that I cannot apply a patch with the docker-maven-plugin because it replaces /opt/jboss/wildfly and does not add to it.

To reproduce, please build

https://github.com/tdiesler/wildfly-camel/tree/docker-mvn-plugin

In [docker/pom.xml](https://github.com/tdiesler/wildfly-camel/blob/docker-mvn-plugin/docker/pom.xml#L77) I commented out the wanted target config

**Comment by jgangemi** [comment]
is this still an issue as of the 0.11.1 release?
