### ISSUE TITLE
Respect "autoPull" when building images

### ISSUE THREAD

**Issue by rhuss** [rhuss/docker-maven-plugin#77]
When building images, the base image specified with `from` should be pulled as well if `autoPull` is set. Currently `autoPull` works only for `docker:start`.

See also #76

**Comment by jgangemi** [comment]
where does this and #76 fall on your priority list / what you are currently working on? 

i am definitely going to need this in the coming days/weeks and don't want to duplicate efforts if you're already working on it.

**Comment by jgangemi** [comment]
lol - looks like someone else has tackled this :)

**Comment by kuhnroyal** [comment]
Yea, please check if that fixes your issues.

**Comment by rhuss** [comment]
Fixed in 0.11.1
