### ISSUE TITLE
udp port mapping not working

### ISSUE THREAD

**Issue by arnestorksen** [rhuss/docker-maven-plugin#83]
Using docker command-line, it is possible to bind udp ports. The syntax for this is to append /udp to the port number. The plugin does not support this.

I'm trying to use this configuration:
```xml
<image>
    <name>progrium/consul:latest</name>
    <alias>consul</alias>
    <run>
        <volumes>
            <bind>
                <volume>/var/run/docker.sock:/tmp/docker.sock</volume>
            </bind>                                
        </volumes>                                
        <ports>
            <port>8400:8400</port>
            <port>8500:8500</port>
            <port>8600:53/udp</port>
        </ports>
    </run>
</image>

```

I get this error:
Cannot parse port mapping: Port mappings must be given in the format
```
<hostPort>:<mappedPort> or <bindTo>:<hostPort>:<mappedPort>
```
The syntax is mentioned here:
[https://docs.docker.com/userguide/dockerlinks/](https://docs.docker.com/userguide/dockerlinks/)

*You can also bind UDP ports by adding a trailing /udp. For example:*
```
$ sudo docker run -d -p 127.0.0.1:5000:5000/udp training/webapp python app.py
```

**Comment by rhuss** [comment]
Thanks for the report, I'm going to fix this for the next version.

**Comment by jgangemi** [comment]
this has been fixed - closing

**Comment by tmckeag** [comment]
Just reproduced this issue with 0.16.4.  Error message is a little different.  The value 
`<port>43366/udp</port> `
Yields 
`Non numeric port 43366/udp specified in port mapping: For input string: "43366/udp"`
