### ISSUE TITLE
Entrypoint does not support arguments

### ISSUE THREAD

**Issue by jamesnetherton** [rhuss/docker-maven-plugin#84]
Unless I'm missing something obvious, entrypoint does not seem to support arguments. For example if I configure the plugin like the following:
```
<configuration>
  <images>
    <image>
      <name>ubuntu</name>
      <alias>test-container</alias>
      <run>
        <entrypoint>/bin/echo hello world</entrypoint>
      </run>
    </image>
  </images>
</configuration>
```
The build fails with:
```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.0:start (start-containers) on project docker-maven-plugin-entrypoint: Error while calling docker: Starting container with id 3e9420f4ff87b0213147eb165ab021b2889943ecf4fe0bb4d8f114b616b946fa (Not Found: 404)
```
However , the build runs fine if I remove the arguments from entrypoint. Not sure if this is intentional but entrypoint should support arguments just like the normal command configuration.

I've fixed this on my fork in this commit 63f8165200a2b5d596366d3be00395674c315e40. If you're happy to accept a PR, let me know.

**Comment by rhuss** [comment]
Yes, you are right. I will going to fix that for the next release and copy over your fix directly into the integration branch (if you don't mind) . So no need for a PR.

Thanks ...

**Comment by jamesnetherton** [comment]
Yes, no problem. Thanks!
