### ISSUE TITLE
allow a 'global' port properties file configuraiton option

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#90]
right now the `portPropertyFile` needs to be specified on a per `run` basis for images which means i need to load/read multiple files instead of just one.

as an enhancement, we should support defining a global `portPropertyFile` element for all images.

the behavior will be similar to that of the registry configuration, if the image specifies the element it will take precedence over what is globally defined.

**Comment by rhuss** [comment]
If both are given, should the image specific property file override to the global one or should both be merged (and only a specific container port mapping overrides a global mapping) ?

Maybe we can define a 'default' `<run>` configuration on the global level so that also for other properties defaults can be specified ?

**Comment by jgangemi** [comment]
i based this on how the registry is handled where the more specific value takes precedence, so i think from a consistency standpoint we should stick w/ that.

i'm also not sure i understand the other questions - i'm only proposing the global `portPropertyFile` element here that will override the properties file that the dynamic port values get written to.

are you suggesting we offer a way to default values for various `run` options, such as defining a global 'wait' that will apply to all containers that could then be overwritten? 

if yes, i like that idea a lot b/c i think `env` vars would be a perfect fit. if no, please explain. :)

**Comment by rhuss** [comment]
Ok, understand. Its about *writing out* the port properties only (so, of course merigng is not needed here). Sorry, misunderstood my own plugin ;-). Think thats a good idea. I have still other things with higher prio, so if you like it, a PR is welcome (as always ;-)

For the global `<run>` stuff it's probably a bit over the top (one has to explain it and debugging becomes harded), but a global `<env>`  might be nice (but then again, for `build`, `run` or both ?)
