### ISSUE TITLE
Standalone Stop does nothing when image name does not have tag

### ISSUE THREAD

**Issue by BigSocial** [rhuss/docker-maven-plugin#93]
The standalone usage of Stop ("If called in a separate run it will stop (and destroy) all containers which were created from images which are configured for this goal.") will not find the container when the image name does not define a tag. 

This is, if pom.xml looks like this

`<image>...
<name>test</name>
...</image>`

the standalone version of Stop will fail to find it because it's actually called test:latest in Docker.

**Comment by jgangemi** [comment]
is this still the case w/ 0.11.1?

**Comment by rhuss** [comment]
Related to #87, will be fixed there.
